### ISSUE TITLE
Supplicant.breathe() 远程崩溃

### ISSUE THREAD

**Issue by lcatro** [shawn-hou/supplicant#2]
这个崩溃是由于代码里没有检验接收到的数据包的长度而导致的,下面分析原因:

`
udpSocket = new DatagramSocket(3848);
`

  在initUdpSocket() 里,DatagramSocket() 只是绑定了本端口,没有针对限制数据接收来源IP 地址,于是任意IP 都可以往这里发送数据..

    udpSocket.send(datagramPacket);
    byte[] buffer = new byte[4096];
    DatagramPacket dp = new DatagramPacket(buffer, 0, buffer.length);
    **udpSocket.receive(dp);**  //  注意任意IP 地址发送过来的数据这里都会被接收
    int bufferSize = dp.getLength();
    byte[] recvPacket = decrypt(Arrays.copyOf(buffer, bufferSize));
    byte[] recvMd5 = new byte[16];
    for (int j = 2; j < 18; j++) {  //  WARNING ! Crash ..
        recvMd5[j - 2] = recvPacket[j];
        recvPacket[j] = 0;
    }

于是构造短数据即可引发**java.lang.ArrayIndexOutOfBoundsException** 异常,测试代码如下:

    from socket import *
    
    sock = socket(AF_INET,SOCK_DGRAM)

    sock.sendto(b'AAAA',('127.0.0.1',3848))

**Comment by lyq1996** [comment]
活捉大牛…

感觉没有任何蝴蝶在您面前是安全稳定不崩溃的，哈哈哈哈哈哈「doge」

如果这里加入接受数据源ip地址校验应该就可以规避了吧

**Comment by lcatro** [comment]
@lyq1996 哈哈哈,其实是看到@xingrz star 了项目然后过来看看的,这和蝴蝶没有关系,问题在于代码里面有些地方没有考虑周到而导致的,在这里指出也是希望作者可以更加完善的代码.

至于加入地址校验是对的做法,后面的逻辑就可以保证数据来自于正确的来源(其实UDP 是可以伪造来源IP 的,TCP 则不会,原理是UDP 不需要建立连接[只发送一次数据包],TCP 需要建立连接[需要多次数据交互,这个时候回应的数据会发向被伪造的那个地址]).

但是JAVA 有些奇怪,按道理说用UDP 接收数据的时候除了返回数据也还应该返回对方的来源地址,C socket 和python socket 都是这样设计的,但是JAVA 需要在初始化的时候指定,感觉后面的数据来源都很容易受影响呀.
